name: CI

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.2
      - run: |
          if helm plugin list | grep -q 'unittest'; then
            helm plugin update unittest
          else
            helm plugin install https://github.com/helm-unittest/helm-unittest.git
          fi
      - run: helm unittest -t JUnit -o test-output.xml . 
      - run: helm lint .
